stages:
  - install
  - build
  - quality

variables:
  PNPM_STORE_PATH: frontend/.pnpm-store

default:
  image: node:20
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-9 --activate
    - cd frontend
    - pnpm config set store-dir $PNPM_STORE_PATH
  cache:
    key:
      files:
        - frontend/pnpm-lock.yaml
    paths:
      - $PNPM_STORE_PATH

install:
  stage: install
  script:
    - pnpm install --frozen-lockfile
  artifacts:
    paths:
      - frontend/node_modules/
      - frontend/pnpm-lock.yaml
      - frontend/.pnpm-store

eslint:
  stage: quality
  script:
    - pnpm lint
  dependencies:
    - install

types:
  stage: quality
  script:
    - pnpm typecheck
  dependencies:
    - install

test:
  stage: quality
  script:
    - pnpm test:run
  dependencies:
    - install